#Makefile for prec.c

P=atm											#binary name
CFLAGS= -Wall -Wpedantic -Werror -Wextra -g		#all flags that testmachine uses plus -g
CC=c99											#used standard is C99
OBJECTS=
LDLIBS=

$(p): $(OBJECTS)
