# Makefile for the whole task block three
#
# softbobo 03 May 2019

CPPFLAGS= -pedantic -Wextra -Wall -g
OBJECTS= 3-main.o 3-1.cpp 3-2.cpp 3-3.cpp 3-4.cpp 3-5.cpp 3-6.cpp 3-7.cpp 3-9.cpp 3-16.cpp

all: $(OBJECTS)
	g++ $(CPPFLAGS) -o list $(OBJECTS)

3-main.o: 3-main.cpp
	g++ $(CPPFLAGS) -c 3-main.cpp

3-1.o: 3-1.cpp
	g++ $(CPPFLAGS) -c 3-1.cpp

3-2.o: 3-2.cpp	
	g++ $(CPPFLAGS) -c 3.2.cpp

3-3.o: 3-3.cpp
	g++ $(CPPFLAGS) -c 3-3.cpp

3-4.o: 3-4.cpp
	g++ $(CPPFLAGS) -c 3-4.cpp

3-5.o: 3-5.cpp
	g++ $(CPPFLAGS) -c 3-5.cpp

3-6.o: 3-6.cpp
	g++ $(CPPFLAGS) -c 3-6.cpp

3-7.o: 3-7.cpp
	g++ $(CPPFLAGS) -c 3-7.cpp

3-9.o: 3-9.cpp
	g++ $(CPPFLAGS) -c 3-9.cpp

3-16.o: 3-16.cpp
	g++ $(CPPFLAGS) -c 3-16.cpp