# Makefile for the whole task block three
#
# softbobo 03 May 2019

CPPFLAGS= -pedantic -Wextra -Wall 
OBJECTS= 3-main.o 3-1.cpp 3-3.cpp 3-5.cpp

all: $(OBJECTS)
	g++ $(CPPFLAGS) -o list $(OBJECTS)

3-main.o: 3-main.cpp
	g++ $(CPPFLAGS) -c 3-main.cpp

3-1.o: 3-1.cpp
	g++ $(CPPFLAGS) -c 3-1.cpp

3-3.o: 3-3.cpp
	g++ $(CPPFLAGS) -c 3-3.cpp

3-5.o: 3-5.cpp
	g++ $(CPPFLAGS) -c 3-5.cpp

3-7.o: 3-7.cpp
	g++ $(CPPFLAGS) -c 3-7.cpp

3-9.o: 3-9.cpp
	g++ $(CPPFLAGS) -c 3-9.cpp