# Makefile for the whole task block three
#
# softbobo 03 May 2019

CPPFLAGS= -pedantic -Wextra -Wall 
OBJECTS= 3-main.o 3-1.cpp

all: $(OBJECTS)
	g++ $(CPPFLAGS) -o list $(OBJECTS)

3-main.o: 3-main.cpp
	g++ $(CPPFLAGS) -c 3-main.cpp

3-1.o: 3-1.cpp
	g++ $(CPPFLAGS) -c 3-1.cpp
